# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  dwproton-x64-linux = {
    pname = "dwproton-x64-linux";
    version = "11.0-9";
    src = fetchzip {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-9/dwproton-11.0-9-x86_64.tar.xz";
      sha256 = "sha256-kWMYlF0H9iYjRcKmq/G4Ws4sTl+gN8nSFgfYvAOd754=";
    };
  };
  faugus-launcher = {
    pname = "faugus-launcher";
    version = "2.0.2";
    src = fetchFromGitHub {
      owner = "Faugus";
      repo = "faugus-launcher";
      rev = "2.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-0knobTbMLOkRIGze+gHaee2Duq4ClMapTCzICX35A8s=";
    };
  };
  helium-browser-arm64-linux = {
    pname = "helium-browser-arm64-linux";
    version = "0.14.8.2";
    src = fetchzip {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.8.2/helium-0.14.8.2-arm64_linux.tar.xz";
      sha256 = "sha256-PZXFVQEa7svZWwW+6haLtofjdQywKT1JtDqdICfCwoo=";
    };
  };
  helium-browser-x64-linux = {
    pname = "helium-browser-x64-linux";
    version = "0.14.8.2";
    src = fetchzip {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.8.2/helium-0.14.8.2-x86_64_linux.tar.xz";
      sha256 = "sha256-wNsdkZIJGC2AtaoLsMAFVQ3MrkYOcwbUtbyfZkNhyTE=";
    };
  };
  hydralauncher = {
    pname = "hydralauncher";
    version = "4.0.6";
    src = fetchurl {
      url = "https://github.com/hydralauncher/hydra/releases/download/v4.0.6/hydralauncher-4.0.6.AppImage";
      sha256 = "sha256-LQ2z8yUUhKLs98YvHHLnhqqtcJFGIvEQ19kB5l0Ti9E=";
    };
  };
  netbird = {
    pname = "netbird";
    version = "0.74.7";
    src = fetchzip {
      url = "https://github.com/netbirdio/netbird/archive/v0.74.7.tar.gz";
      sha256 = "sha256-Rmi54gS1yOlbBYUUit49p5WwnhfwPd/G5Wq209Wdv/4=";
    };
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
    src = fetchFromGitHub {
      owner = "thou-vow";
      repo = "nvfetcher";
      rev = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
      fetchSubmodules = false;
      sha256 = "sha256-9PQK8mnzZoMUHPsY7PcFP0WoqhlHZzxjpTPdB6H+TOg=";
    };
    date = "2026-06-08";
  };
  proton-cachyos-x64-linux = {
    pname = "proton-cachyos-x64-linux";
    version = "11.0-20260703-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260703-slr/proton-cachyos-11.0-20260703-slr-x86_64.tar.xz";
      sha256 = "sha256-jOcPeEkBBPPNqyjXBoHm1Nk8AexPiLhx5+385NjUPT0=";
    };
  };
  proton-cachyos-x64-linux-v3 = {
    pname = "proton-cachyos-x64-linux-v3";
    version = "11.0-20260703-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260703-slr/proton-cachyos-11.0-20260703-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-8Y7orUvnFOG0zSqCrMyvmclmy3JInj7d8A2h0Y7RwhE=";
    };
  };
  proton-ge-x64-linux = {
    pname = "proton-ge-x64-linux";
    version = "11-1";
    src = fetchzip {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-1/GE-Proton11-1.tar.gz";
      sha256 = "sha256-I7SSvzQQ/NqdvwjpJ9IFFtAaTS+rgHUyXx0us1vIOnw=";
    };
  };
  treefmt-nix = {
    pname = "treefmt-nix";
    version = "df3c0640565d04a0261253cdd89fce78ec50168a";
    src = fetchFromGitHub {
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "df3c0640565d04a0261253cdd89fce78ec50168a";
      fetchSubmodules = false;
      sha256 = "sha256-47cxbcZODibHv3rELFQ9vZly0vUNkND/atn/U7HLeb0=";
    };
    date = "2026-07-18";
  };
}
