# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}: {
  dwproton-x64-linux = {
    pname = "dwproton-x64-linux";
    version = "11.0-7";
    src = fetchzip {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-7/dwproton-11.0-7-x86_64.tar.xz";
      sha256 = "sha256-M8wcC7pKFs0Qena5NN9ylq2TykRfPK7JiHnzP6DkZv0=";
    };
  };
  faugus-launcher = {
    pname = "faugus-launcher";
    version = "2.0.0";
    src = fetchFromGitHub {
      owner = "Faugus";
      repo = "faugus-launcher";
      rev = "2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-VHf9hO984Q2nNHNVm8UqmZQypxKY8FSOzAHceliUhTA=";
    };
  };
  helium-browser-arm64-linux = {
    pname = "helium-browser-arm64-linux";
    version = "0.14.7.1";
    src = fetchzip {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.7.1/helium-0.14.7.1-arm64_linux.tar.xz";
      sha256 = "sha256-L7MoE8q6o/V6z2ZHMks0I/aZLi94ybv+90VcHYL3dVc=";
    };
  };
  helium-browser-x64-linux = {
    pname = "helium-browser-x64-linux";
    version = "0.14.7.1";
    src = fetchzip {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.7.1/helium-0.14.7.1-x86_64_linux.tar.xz";
      sha256 = "sha256-fJDwfUJChM9Fl7mckDKI7oIe5rG7+P11AdEkd+MlN3o=";
    };
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
    src = fetchFromGitHub {
      owner = "thou-vow";
      repo = "nvfetcher";
      rev = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
      fetchSubmodules = false;
      sha256 = "sha256-9PQK8mnzZoMUHPsY7PcFP0WoqhlHZzxjpTPdB6H+TOg=";
    };
    date = "2026-06-08";
  };
  proton-cachyos-x64-linux = {
    pname = "proton-cachyos-x64-linux";
    version = "11.0-20260702-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260702-slr/proton-cachyos-11.0-20260702-slr-x86_64.tar.xz";
      sha256 = "sha256-ZyyhEf6NcW7MzswWAlMdE4Ok8KnBOmB81yvu8ZwVxl4=";
    };
  };
  proton-cachyos-x64-linux-v3 = {
    pname = "proton-cachyos-x64-linux-v3";
    version = "11.0-20260702-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260702-slr/proton-cachyos-11.0-20260702-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-pbx/WDgpa55WDr1exD4rrNWsRoVkqHIUjzX1PJObxG8=";
    };
  };
  proton-ge-x64-linux = {
    pname = "proton-ge-x64-linux";
    version = "11-1";
    src = fetchzip {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-1/GE-Proton11-1.tar.gz";
      sha256 = "sha256-I7SSvzQQ/NqdvwjpJ9IFFtAaTS+rgHUyXx0us1vIOnw=";
    };
  };
  treefmt-nix = {
    pname = "treefmt-nix";
    version = "df3c0640565d04a0261253cdd89fce78ec50168a";
    src = fetchFromGitHub {
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "df3c0640565d04a0261253cdd89fce78ec50168a";
      fetchSubmodules = false;
      sha256 = "sha256-47cxbcZODibHv3rELFQ9vZly0vUNkND/atn/U7HLeb0=";
    };
    date = "2026-07-18";
  };
}
